### PR TITLE
Remove `physical variant` and `momentary_positions`

### PR DESCRIPTION
**Pull request by emcek**
* remove `PhysicalVariant` enum and usage of `physical variant`
* remove `MomentaryPositions` enum and usage of `momentary_positions`
* update unit tests
* clean up documentation
* Fix for issue #532

### CODE REVIEW

**Comment by jdahlblom** [comment]
@charliefoxtwo, at some point that archive should be removed or zipped.

**Comment by jdahlblom** [comment]
@emcek, ```C-101```, ```NS430``` and ```Module.lua``` still have the removed parameter in calls to ```Control:new```.

**Comment by emcek** [comment]
@jdahlblom 
1. Can't see where removed parameters are still present
2. Not sure why one test if failing, looks right to me

I do not have local lua dev env. running :/

**Comment by jdahlblom** [comment]
> @jdahlblom ~1. Can't see where removed parameters are still present~ ~2. Not sure why one test if failing, looks right to me~
> 
> I do not have local lua dev env. running :/
> 
> I think I got it. Please review.

Yup, looks good. I generated the new JSON files. How do we get that into this PR? I don't know git that well. Can I push to this PR?

**Comment by jdahlblom** [comment]
Hmm I pushed to this PR but can't see the commit.

**Comment by charliefoxtwo** [comment]
Yeah none of the files in the archive folder need to be (nor should be) changed. @jdahlblom youre right, we should just remove it entirely - the new modules have been working just fine.

**Comment by jdahlblom** [comment]
Github is lagging, my commit will show up later.

**Comment by emcek** [comment]
> Yeah none of the files in the archive folder need to be (nor should be) changed. @jdahlblom youre right, we should just remove it entirely - the new modules have been working just fine.

So, I will revert them, to be clean in separate PR.

**Review by jdahlblom — APPROVED** [review]

**Review by charliefoxtwo — APPROVED** [review]
Looks great, thank you for doing this! Now to remove `api_variant`...

**Pull request merged**
