### PR TITLE
Set RTS option and explain its effect

### PR DESCRIPTION
**Pull request by michaelosthege**
I struggled with unreliable connection initialization with my ESP32-based panel.
The command line was sometimes all garbled up and sometimes not.

My ESP32 was restarting every time the COM port was opened/closed, and since it takes ~10 seconds to initialize, it wouldn't reliably establish the connection.

I found that `DTS` and `RTS` are both misused as a reset signal, and after setting `RTS=off` the restarts disappeared and the connection not initializes reliably.

To help other people I would propose to set the `RTS` option explicitly.

### CODE REVIEW

**Comment by charliefoxtwo** [comment]
Could you elaborate more on what the RTS option does? I'm not familiar with most of the arduino and COM stuff, but I haven't heard any reports about any other users experiencing the issue you've described so I'd be hesitant to merge something which - while it may fix an issue for one individual - may cause issues for many others.

I'm _assuming_ based on your description that the RTS value is set to on by default so this PR doesn't actually change anything other than expose a new option which may help people, but if that's the case I'd appreciate it if you could link to additional documentation. Thanks!

**Comment by michaelosthege** [comment]
This thread explains the original purpose of these flags: https://stackoverflow.com/questions/957337/what-is-the-difference-between-dtr-dsr-and-rts-cts-flow-control

This thread shows a wiring diagram for ESP-8266 boards (https://arduino.stackexchange.com/a/52175) and explained that it's used to reset the microcontroller. Apparently that's the same for my ESP-32.

The `mode` command in the script sets the COM device setting, and for me it always printed `RTS=on` until I set the option. It's help shows:

```
mode /?
Configures system devices.

Serial port:       MODE COMm[:] [BAUD=b] [PARITY=p] [DATA=d] [STOP=s]
                                [to=on|off] [xon=on|off] [odsr=on|off]
                                [octs=on|off] [dtr=on|off|hs]
                                [rts=on|off|hs|tg] [idsr=on|off]
```

Unfortunately the [documentation](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mode#parameters) does not clarify the defaults either.

**Comment by charliefoxtwo** [comment]
I'm really hesitant to merge this without knowing what the default is.

It doesn't help that it's like impossible to look up anything for the command because it's named `mode` lol

**Comment by michaelosthege** [comment]
Could be that the default is whatever was previously set for that COM port.

Let's just keep the comment then, and not actually set the option.

**Review by michaelosthege — COMMENTED** [review]
Rephrase comment and don't set the RTS option

**Comment by charliefoxtwo** [comment]
I'm all for improved documentation. The docs you linked also said `hs | tg` were valid options - did you want to add those as well (or maybe they just don't work in this context, I wouldn't know)?

**Comment by michaelosthege** [comment]
I understand that DCS-BIOS does not implement the interpretation of these signals, there fore I don't expect them to be useful at this point.

**Pull request merged**
