### PR TITLE
F-4E: Add Circuit Breakers

### LINKED ISSUE #644: F-4E Circuit Breakers Device

### PR DESCRIPTION
**Pull request by charliefoxtwo**
Fixes #644

@acstott I went ahead and cherry-picked your commit and then regenerated the Addresses file, so you're still the author of the work you did. If you're ok with this, I'll merge it.

### CODE REVIEW

**Comment by acstott** [comment]
Thanks - were you able to generate the file correctly? I still need to understand why it was generating differently for me as the plan was to work on some simple open tasks for the Kiowa next

**Comment by charliefoxtwo** [comment]
Yeah it generates fine for me - you can see it only has ~150 lines changed in the Files Changed tab.

Hopefully we can get it working for you - help with the Kiowa would be very much appreciated!

**Comment by acstott** [comment]
Ok, I'll take a look at the open issues tomorrow and select a few and you can let me know priority and ease of implementation and I'll pick one up next week

**Comment by acstott** [comment]
Forgot to comment that yes you can go ahead and merge it - thanks!

**Pull request merged**
