### PR TITLE
Added two scripts to log and replay com-port data for easier hardware testing

### PR DESCRIPTION
**Pull request by maciekish**
These scripts allow easy logging and replaying of DCS-BIOS data over the com-port. It makes it easy to for example mass-test MAX487 chips without having to run DCS World in the background all the time.

Just record some data with `python connect-logger.py`, for example the master caution light blinking, and then run `python replay-log.py` and it will loop the data forever to your selected com-port. The file is saved as `dcsbios_data.json` in the same folder.

Here is a replay of the A-10C Master Caution blinking D13 on a Nano without DCS World running:

https://github.com/DCS-Skunkworks/dcs-bios/assets/442007/6584864e-7e9b-40b0-8d24-99c436968770

### CODE REVIEW

**Comment by jdahlblom** [comment]
OK. Is it usually warlord who merges these? Know nothing about what is under programs. Looks useful.

**Comment by maciekish** [comment]
> OK. Is it usually warlord who merges these? Know nothing about what is under programs. Looks useful.

I think so, it doesn't change anything, just adds two scripts so at least it wont break anything.

**Comment by talbotmcinnis** [comment]
Cool tool, thanks.  I'd just want to see some documentation make it in along with the scripts.  Main readme?

**Comment by WarLord211** [comment]
Reads Cool indeed!! Thanks for that!

Like @talbotmcinnis said I little documentation would be cool.

What ist it? how to use?

**Comment by maciekish** [comment]
@talbotmcinnis @WarLord211 I have added documentation to the readme, moved the files to `Programs\tools` to avoid cluttering `Programs` and added a sample recording.

**Comment by WarLord211** [comment]
perfect thank you for this

**Pull request merged**
