### PR TITLE
#50 Right-align IFEI fuel text

### PR DESCRIPTION
**Pull request by charliefoxtwo**
**This may be a breaking change**. If it is and this is undesirable, an alternative #221 is also available, which I recommend and prefer. We should **only merge one**.

This changes right-aligned strings from being exported like `500___` to `___500` (where underscores are spaces).

This could be a breaking change depending on how users are parsing this data, as the text will now have spaces before it instead of after it. However, it's definitely more correct to right-align them (as this is how they're displayed in the plane) and will result in significantly fewer headaches for new users.

This also fixes a bug in `padLeft()` which could result in `nil` being actually displayed as the text `"nil"`

### CODE REVIEW

**Comment by WarLord211** [comment]
I would Hand his to a panelbuilder for testing.
Than we can say how mich impact this change generate

**Comment by charliefoxtwo** [comment]
Great idea. Maybe even more than one.

If it's a problem, one alternative might be to just create new fields. The new fields can also be mapped to the display output rather than the individual data items as well, which might make more sense.

**Comment by WarLord211** [comment]
i know two who build use/sell the affected panel

**Comment by charliefoxtwo** [comment]
Created an alternative - #221. It creates new entries for the right-aligned fields and condenses the cases where we had multiple data elements for the same display area.

**Pull request merged**
