### PR TITLE
Mirage F1 Controls updated

### PR DESCRIPTION
**Pull request by jdahlblom**
- P_ALT_PTT
- UHF_RADIO

### CODE REVIEW

**Review by charliefoxtwo — CHANGES_REQUESTED** [review]
Lots of address/mask changes here and we should try to avoid that is possible. Any idea what caused it? 
Yes, one control had limits changed from `{0 - 1}` to `{0 - 0.5}`. Is that the culprit? Don't know if dcs-bios allocates smaller memory space than 1 byte.
I had originally changed the ordering of `P_CE_IFF_POS_IDENT` but moved it back.

**Comment by jdahlblom** [comment]
Apart from the memory space changes this module should be OK with the unified release.

**Comment by jdahlblom** [comment]
> Lots of address/mask changes here and we should try to avoid that is possible. Any idea what caused it?

Yes, one control had limits changed from {0 - 1} to {0 - 0.5}. Is that the culprit? Don't know if dcs-bios allocates smaller memory space than 1 byte.
I had originally changed the ordering of P_CE_IFF_POS_IDENT but moved it back.

**Review by charliefoxtwo — APPROVED** [review]
We should document the following:
### Mirage F1
#### Address/mask changes
- `MirageF1_P_CE_IFF_M1_1` (Updated from 7 positions to 3)
#### Controls renamed

| Old | New |
| - | - |
| `P_CE_IFF_MODE_M4` | `P_CE_IFF_MODE_MC` |

**Pull request merged**
